<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-07-20 12:00

$extensionClassesPath = t3lib_extMgm::extPath('cz_simple_cal') . 'Classes/';
return array(
	//needed by the scheduler
	'tx_czsimplecal_scheduler_index' => $extensionClassesPath . 'Scheduler/Index.php',
	//need for hooks
	'tx_czsimplecal_indexer_event' => $extensionClassesPath . 'Indexer/Event.php',
	'tx_czsimplecal_hook_datamap' => $extensionClassesPath . 'Hook/Datamap.php',
	'tx_czsimplecal_hook_cmdmap' => $extensionClassesPath . 'Hook/Cmdmap.php',
);
?>