<?php

########################################################################
# Extension Manager/Repository config file for ext: "cz_simple_cal"
#
# Auto generated by Extbase Kickstarter 2010-07-19
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple calendar using Extbase',
	'description' => 'A simple calendar.',
	'category' => 'plugin',
	'author' => 'Christian Zenker',
	'author_email' => 'christian.zenker@599media.de',
	'author_company' => '599media GmbH',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'scheduler' => '',
			'tt_address' => ''
		),
	),
);

?>