<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-07-20 12:00

$extensionClassesPath = t3lib_extMgm::extPath('cz_simple_cal') . 'Classes/';
return array(
	'tx_czsimplecal_controller_categorycontroller' => $extensionClassesPath . 'Controller/CategoryController.php',
	'tx_czsimplecal_controller_eventcontroller' => $extensionClassesPath . 'Controller/EventController.php',
	'tx_czsimplecal_domain_model_category' => $extensionClassesPath . 'Domain/Model/Category.php',
	'tx_czsimplecal_domain_model_event' => $extensionClassesPath . 'Domain/Model/Event.php',
	'tx_czsimplecal_domain_repository_categoryrepository' => $extensionClassesPath . 'Domain/Repository/CategoryRepository.php',
	'tx_czsimplecal_domain_repository_eventrepository' => $extensionClassesPath . 'Domain/Repository/EventRepository.php',
	'tx_czsimplecal_indexer_event' => $extensionClassesPath . 'Indexer/Event.php',
	'tx_czsimplecal_indexer_exception' => $extensionClassesPath . 'Indexer/Exception.php',
	'tx_czsimplecal_indexer_base' => $extensionClassesPath . 'Indexer/Base.php',
);
?>